---
title: "Registro Nacional de Denuncias de Delitos y Faltas 2017"
output: 
  flexdashboard::flex_dashboard:
  orientation: columns
vertical_layout: fill
runtime: shiny
---
```{r setup, include=FALSE}
library(foreign)
library(shiny)
library(curl)
library(flexdashboard)
library(readr)
library(raster)
library(ggplot2)
library(dplyr)
library(lubridate)
library(haven)
library(highcharter)
library(maptools)  
library(RColorBrewer) 
library(readxl)
library(leaflet)
library(broom)
library(dplyr)
library(ggplot2)
library(classInt) 
library(sp)
library(rgdal)
library(spdep) 
library(ggpubr)
library(rgeos)
```

```{css}
.value-box {
  height: 85px;
}

```

```{r, results='hide'}
#Ubicamos nuestro directorio de trabajo
setwd("C:/Users/Computer/Documents/restepo")

#Cargamos la base de datos
#Módulo 100
id<- "1lQ8L-mRVcR8nuiOwyaD25aCnod12GiB6"
sURL <- sprintf("https://drive.google.com/uc?id=%s&export=download",id)
con <- curl(sURL)
cap100<-read_sav(con)

#Módulo 200
cap200<-read.spss("200.sav",to.data.frame=T)

# Cargamos el mapa de Perú a nivel provincias:
peru_prov<- readOGR("GADM/gadm36_PER_2.shp")
#Cargamos el mapa de Perú a nivel distrital:
peru_distr <- readOGR("GADM/gadm36_PER_3.shp")

```

Dashboard
===================================================================
  
Column {.sidebar data-width=350}
-----------------------------------------------------------------------
### Número de denuncias de faltas por provincia
  
```{r, message = FALSE, echo = FALSE}

qpal <- colorQuantile("Blues",cap100$FALTAS,n=9)


leaflet(peru_prov) %>%
  addTiles() %>%
  addPolygons(weight = 1,
              stroke = T,
              color = ~qpal(cap100$FALTAS),
              #fillColor = ~qpal(NAME_2),
              fillOpacity = 1,
              smoothFactor = 0.2,
              dashArray = "3",
              label = ~NAME_2,
              popup = ~paste("<b>Provincia:</b>", NAME_2,
                             "<br/>",
                             "<b>Departamento:</b>", NAME_1,
                             "<br/>",
                             "<b>Total de denuncias:</b>",cap100$FALTAS,
                             "<br/>",
                             "<b>Faltas contra la persona:</b>",cap100$FALTAS_A,
                             "<br/>",
                             "<b>Faltas contra el patrimonio:</b>",cap100$FALTAS_B,
                             "<br/>",
                             "<b>Faltas contra las buenas costumbres:</b>",cap100$FALTAS_C,
                             "<br/>",
                             "<b>Faltas contra la seguridad pública:</b>",cap100$FALTAS_D
              ),
              highlight = highlightOptions(
                weight = 2,
                dashArray = "",
                color = "grey",
                bringToFront = TRUE
              )) %>%
  addLegend("bottomleft", pal = qpal, values = ~cap100$FALTAS,
            title = "Número de denuncias",
            labFormat =  function(type, cuts, p) {
              n = length(cuts) 	
              cuts[n] = "mas" 
              for (i in 2:(n-1)){cuts[i] = ""} 	
              cuts[1] = "menos" 
              paste0(cuts[-n], cuts[-1])},
            opacity = 1
  )


```

Column {data-width=300, data-height=600}
-----------------------------------------------------------------------
### Value box 1
  
```{r}


renderValueBox({         
  filtered <- 
    cap200 %>%    
    filter(NOMBREDD == input$Departamento,              
           
    )          
  valueBox(as.numeric(sum(table(filtered$IH208_GENERICO))), "Denuncias de delitos por departamento", icon = "fa-balance-scale", color = "navy")   
})


```


### Value box 2
```{r}
renderValueBox({         
  filtered <- 
    cap200 %>%    
    filter(            
      NOMBREPP == input$Provincia     
      
    )          
  valueBox(as.numeric(sum(table(filtered$IH208_GENERICO))), "Denuncias de delitos por provincia", icon = "fa-balance-scale", color = "blue")   
})


```

### Value box 3
```{r}
renderValueBox({         
  filtered <- 
    cap200 %>%    
    filter(     
      NOMBREDI == input$Distrito
    )          
  valueBox(as.numeric(sum(table(filtered$IH208_GENERICO))), "Denuncias de delitos por distrito", icon ="fa-balance-scale", color = "purple")   
})


```


### Seleccione el distrito
```{r}
selectizeInput("Departamento", label = "Departamento:",
               choices =unique(cap200[c("NOMBREDD")]),selected = "Amazonas")

selectizeInput("Provincia", label = "Provincia:",
               choices=NULL,options = list(maxOptions = 2000000))

selectizeInput("Distrito", label = "Distrito:",
               choices=NULL,options = list(maxOptions = 2000000))

observeEvent(input$Departamento,
             updateSelectizeInput(session,"Provincia","Provincia",choices=cap200$NOMBREPP[cap200$NOMBREDD==input$Departamento], server = TRUE))

observeEvent(input$Provincia,
             updateSelectizeInput(session,"Distrito","Distrito",choices=cap200$NOMBREDI[cap200$NOMBREPP==input$Provincia & cap200$NOMBREDD==input$Departamento], server = TRUE))
```




Column {data-width=500}
-----------------------------------------------------------------------
### Evolución de tipos de denuncias de delitos por distrito
```{r}

b <- reactive({as.data.frame(table(cap200[which(cap200$NOMBREDI==input$Distrito),]$IH203_MES,cap200[which(cap200$NOMBREDI==input$Distrito),]$IH208_GENERICO ))})
renderPlot({ ggplot(as.data.frame(b()), aes(x=Var1,y = Freq,group = Var2 ))+
    geom_line(aes(color = Var2))+
    geom_point(aes(color = Var2), size=2, shape=21, fill="white")+
    geom_label(aes(label=b()$Freq),size = 3)+
    xlab("Mes") +   
    ylab("Cantidad de denuncias reportadas") + 
    theme(legend.position = "bottom",legend.text = element_text(size = 5))+
    scale_x_discrete(labels = c("ENE", "FEB","MAR","ABR","MAY","JUN","JUL","AGO","SET",
                                "OCT","NOV","DIC", "S/F"))
})

```   

### Tipos de denuncias de delitos  por distrito

```{r}
a <- reactive({as.data.frame(sort(table(cap200[which(cap200$NOMBREDI==input$Distrito),]$IH208_GENERICO),decreasing = T))})

theme_set(theme_classic())
# Plot
renderPlot({
  ggplot(as.data.frame(a()), aes(x=Var1, y=Freq)) +
    geom_point(col="tomato2", size=3) +   # Draw points
    geom_text(label=a()$Freq, check_overlap = T,nudge_x = 0.30)+
    geom_segment(aes(x=Var1,
                     xend=Var1,
                     y=min(Freq),
                     yend=max(Freq)),
                 linetype="dashed",
                 size=0.1) +   # Draw dashed lines
    labs(title="Delitos Cometidos en el Distrito") +
    coord_flip() +labs(x= "Delitos", y = "Cantiad de Denuncias")
})

```
